version: '3.9'

services:
  backend:
    build: .
    container_name: pas-backend
    command: node server.js
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: pas
      DB_PORT: 5432
    ports:
      - "3500:3000"
    volumes:
      - ./uploads:/usr/src/app/uploads
      - .env:/usr/src/app/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: pas-db
    restart: always
    environment:
      POSTGRES_DB: pas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata: